# Generated by Django 4.2.3 on 2023-08-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_add_field_to_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
